# This branch works with Windows only

name: ndgs
channels:
  - pytorch
  - nvidia/label/cuda-12.4.1
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.4
  - lightning
  - numpy=1.23.5
  - plyfile
  - pip=22.3.1
  - python=3.9
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - tensorboard